trigger:
  branches:
    include:
      - master

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the Function App'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - script: |
        dotnet restore
        dotnet build --configuration Release
      displayName: 'Build the Azure Function'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'


- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: |
        dotnet test --configuration Release
      displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy to Azure'
  jobs:
  - job: Deploy
    displayName: 'Deploy Function to Azure'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'MyAzureServiceConnection'  # Replace with your Azure service connection name
        appName: 'lab4_Azurfunction'               # Replace with your Azure Function App name
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
